name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "30 9 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , windows-latest, macos-latest ]
        python-version: [ 3.8, 3.9, '3.10', '3.11' ]
    steps:
      - name: Checkout alphalens
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install alphalens
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          pip install -e .[test]

      - name: Lint with flake8
        run: |
          flake8

      - name: Unittests with tox & pytest
        run: |
          tox

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
